server:
  port: 8080

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Codecracker508/git-config-repo
          repos:
            staging-properties-repo:
              pattern: user-service/stage
              uri: https://github.com/Codecracker508/git-config-repo
              search-paths:
                - user-service
            test-properties-repo:
              pattern: user-service/test
              uri: https://github.com/Codecracker508/git-config-repo
              search-paths:
                - user-service
          default-label: main